[phases.setup]
nixPkgs = ["stdenv.cc.cc.lib", "gcc"]

[variables]
LD_LIBRARY_PATH = "/nix/var/nix/profiles/default/lib:/root/.nix-profile/lib"

[start]
cmd = "python -m uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000}"
